### ISSUE TITLE
Forbidden request from remote IP address: x.x.x.x.. Does not match 

### ISSUE THREAD

**Issue by smilelikeshit** [certera-io/certera#22]
I already install certera on VPS but when im access using https://x.x.x.x , I have error like this

Forbidden request from remote IP address: x.x.x.x. Does not match

**Comment by certeraio** [comment]
This is due to a security feature to ensure no unauthorized IP can access without your explicit knowledge and permission. If you add the IP here: https://github.com/certera-io/certera/blob/master/src/Certera.Web/config.json#L2

You should be able to access. You can also set it to `*` should you want to (and have strong means of securing things).

**Comment by smilelikeshit** [comment]
yes solved thank you for the response @certeraio
