### ISSUE TITLE
User locked after few login attempts

### ISSUE THREAD

**Issue by gik000** [certera-io/certera#5]
How to unlock a user that has failed few login attempts?
Is there a way to do that?

**Comment by certeraio** [comment]
Hi @gik000, 

The user should only be locked out for 5 minutes. Upon a successful login after a lockout (and after 5 minutes has elapsed since the last attempt), the attempt count and clock are reset.

If it's been more than 5 minutes and you still can't get in, please let me know. I'll double check things on my end and run through some tests to confirm.

**Comment by gik000** [comment]
Hi,

thanks for your answer.
I waited 5 minutes and the problem went away.

As improvement, I would suggest to implement a mechanism to unblock the users from command line.

Thanks
